# Generated by Django 6.0.2 on 2026-02-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='numbercar',
            old_name='Number_Car',
            new_name='number_Car',
        ),
        migrations.AddField(
            model_name='numbercar',
            name='tags',
            field=models.ManyToManyField(null=True, to='relation_db.tag'),
        ),
    ]
