# Generated by Django 6.0.2 on 2026-02-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='укажите язык програмирование')),
                ('deskription', models.TextField(verbose_name='укажите описание языка')),
                ('image', models.ImageField(upload_to='proglang/', verbose_name='загрузите фото')),
                ('created_date_lang', models.PositiveIntegerField(blank=True, verbose_name='укажите од создание языка програмирование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'язык прогримирование',
                'verbose_name_plural': 'языки програмирование',
            },
        ),
    ]
