# Generated by Django 6.0.2 on 2026-02-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proglang',
            old_name='deskription',
            new_name='description',
        ),
    ]
