# Generated by Django 6.0.2 on 2026-02-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0002_rename_deskription_proglang_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='proglang',
            name='viki_url',
            field=models.URLField(null=True, verbose_name='вставьте ссылку википедии'),
        ),
    ]
