# Generated by Django 6.0.2 on 2026-02-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0003_proglang_viki_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='proglang',
            name='file_lang',
            field=models.FileField(null=True, upload_to='files/', verbose_name='file'),
        ),
    ]
