# Generated by Django 6.0.2 on 2026-02-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0004_proglang_file_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proglang',
            name='image',
            field=models.ImageField(null=True, upload_to='proglang/', verbose_name='загрузите фото'),
        ),
    ]
